use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;

pub type DriverId = Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DriverMessage {
    #[serde(rename = "register")]
    Register(RegisterRequest),
    #[serde(rename = "heartbeat")]
    Heartbeat(HeartbeatRequest),
    #[serde(rename = "deregister")]
    Deregister(DeregisterRequest),
    #[serde(rename = "command_ack")]
    CommandAck(CommandAck),
    #[serde(rename = "metrics_report")]
    MetricsReport(DriverMetricsReport),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegisterRequest {
    pub capabilities: Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HeartbeatRequest {
    pub driver_id: DriverId,
}

/// Cumulative driver-side metrics. Sent periodically alongside heartbeats.
/// Values are running totals since driver start — the consumer computes
/// deltas between snapshots to derive per-phase or per-interval rates.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DriverMetricsReport {
    pub driver_id: DriverId,
    pub ok: u64,
    pub err: u64,
    pub latency_sum_us: u64,
    pub latency_samples: u64,
    pub max_latency_us: u64,
    pub bytes: u64,
    #[serde(default)]
    pub errors: DriverErrorBreakdown,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DriverErrorBreakdown {
    pub timeout: u64,
    pub not_delivered: u64,
    pub http_status: u64,
    pub transport: u64,
    pub connection_drop: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeregisterRequest {
    pub driver_id: DriverId,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum OrchestratorResponse {
    #[serde(rename = "ack")]
    Ack(AckResponse),
    #[serde(rename = "register_rejected")]
    RegisterRejected(RegisterRejectedResponse),
    #[serde(rename = "error")]
    Error(ErrorResponse),
    /// Server-pushed command (real-time C2 dispatch). Driver applies the
    /// command and replies with `DriverMessage::CommandAck { command_seq }`.
    #[serde(rename = "command")]
    Command(CommandEnvelope),
}

/// Wire envelope for a server-pushed command. The `seq` is generated by the
/// orchestrator (`CommandDispatcher::submit`) and echoed back in the
/// driver's `CommandAck` so the dispatcher can match acks to submissions.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CommandEnvelope {
    pub seq: u64,
    pub command: OrchestratorCommand,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AckResponse {
    pub driver_id: Option<DriverId>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegisterRejectedResponse {
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorResponse {
    pub message: String,
}

// -----------------------------------------------------------------------------
// Orchestrator → driver commands (real-time command dispatch, C2).
//
// The orchestrator carries no benchmark vocabulary. Commands are domain-neutral
// instructions a controller can submit at any time. Initial set is the minimum
// required to recreate today's benchmark behavior; new commands get added when
// a controller needs them.
// -----------------------------------------------------------------------------

/// Command pushed from the orchestrator to a registered driver. The driver
/// applies the command and acknowledges via `CommandAck` back-message.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "type")]
pub enum OrchestratorCommand {
    /// Set the steady-state player count on the driver. The driver adjusts
    /// its local fleet slice to match its share of the global target.
    #[serde(rename = "set_players")]
    SetPlayers(SetPlayersCommand),
    /// Set the inter-spawn delay used while ramping the player count up
    /// (mirrors the existing `--inter-spawn-delay-ms` flag from PR #17).
    #[serde(rename = "set_spawn_delay_ms")]
    SetSpawnDelayMs(SetSpawnDelayMsCommand),
    /// Tear down the local fleet slice, flush telemetry, deregister.
    #[serde(rename = "stop")]
    Stop,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SetPlayersCommand {
    pub player_count: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SetSpawnDelayMsCommand {
    pub spawn_delay_ms: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CommandAck {
    pub driver_id: DriverId,
    pub command_seq: u64,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn register_request_json_round_trip() {
        let original = DriverMessage::Register(RegisterRequest {
            capabilities: json!({"platform": "linux", "cores": 8}),
        });

        let json = serde_json::to_string(&original).unwrap();
        let deserialized: DriverMessage = serde_json::from_str(&json).unwrap();

        assert_eq!(
            serde_json::to_value(&original).unwrap(),
            serde_json::to_value(&deserialized).unwrap()
        );
    }

    #[test]
    fn heartbeat_request_json_round_trip() {
        let driver_id = Uuid::new_v4();
        let original = DriverMessage::Heartbeat(HeartbeatRequest { driver_id });

        let json = serde_json::to_string(&original).unwrap();
        let deserialized: DriverMessage = serde_json::from_str(&json).unwrap();

        assert_eq!(
            serde_json::to_value(&original).unwrap(),
            serde_json::to_value(&deserialized).unwrap()
        );
    }

    #[test]
    fn deregister_request_json_round_trip() {
        let driver_id = Uuid::new_v4();
        let original = DriverMessage::Deregister(DeregisterRequest { driver_id });

        let json = serde_json::to_string(&original).unwrap();
        let deserialized: DriverMessage = serde_json::from_str(&json).unwrap();

        assert_eq!(
            serde_json::to_value(&original).unwrap(),
            serde_json::to_value(&deserialized).unwrap()
        );
    }

    #[test]
    fn ack_response_json_round_trip() {
        let driver_id = Some(Uuid::new_v4());
        let original = OrchestratorResponse::Ack(AckResponse { driver_id });

        let json = serde_json::to_string(&original).unwrap();
        let deserialized: OrchestratorResponse = serde_json::from_str(&json).unwrap();

        assert_eq!(
            serde_json::to_value(&original).unwrap(),
            serde_json::to_value(&deserialized).unwrap()
        );
    }

    #[test]
    fn register_rejected_response_json_round_trip() {
        let original = OrchestratorResponse::RegisterRejected(RegisterRejectedResponse {
            reason: "Pool at capacity".to_string(),
        });

        let json = serde_json::to_string(&original).unwrap();
        let deserialized: OrchestratorResponse = serde_json::from_str(&json).unwrap();

        assert_eq!(
            serde_json::to_value(&original).unwrap(),
            serde_json::to_value(&deserialized).unwrap()
        );
    }

    #[test]
    fn error_response_json_round_trip() {
        let original = OrchestratorResponse::Error(ErrorResponse {
            message: "Driver not found".to_string(),
        });

        let json = serde_json::to_string(&original).unwrap();
        let deserialized: OrchestratorResponse = serde_json::from_str(&json).unwrap();

        assert_eq!(
            serde_json::to_value(&original).unwrap(),
            serde_json::to_value(&deserialized).unwrap()
        );
    }

    #[test]
    fn register_message_tag_deserialization() {
        let json = r#"{"type":"register","capabilities":{"platform":"linux"}}"#;
        let msg: DriverMessage = serde_json::from_str(json).unwrap();

        match msg {
            DriverMessage::Register(_) => (),
            _ => panic!("Expected Register variant"),
        }
    }

    #[test]
    fn heartbeat_message_tag_deserialization() {
        let driver_id = Uuid::new_v4();
        let json = format!(r#"{{"type":"heartbeat","driver_id":"{}"}}"#, driver_id);
        let msg: DriverMessage = serde_json::from_str(&json).unwrap();

        match msg {
            DriverMessage::Heartbeat(_) => (),
            _ => panic!("Expected Heartbeat variant"),
        }
    }

    #[test]
    fn deregister_message_tag_deserialization() {
        let driver_id = Uuid::new_v4();
        let json = format!(r#"{{"type":"deregister","driver_id":"{}"}}"#, driver_id);
        let msg: DriverMessage = serde_json::from_str(&json).unwrap();

        match msg {
            DriverMessage::Deregister(_) => (),
            _ => panic!("Expected Deregister variant"),
        }
    }

    #[test]
    fn ack_response_tag_deserialization() {
        let json = r#"{"type":"ack","driver_id":null}"#;
        let response: OrchestratorResponse = serde_json::from_str(json).unwrap();

        match response {
            OrchestratorResponse::Ack(_) => (),
            _ => panic!("Expected Ack variant"),
        }
    }

    #[test]
    fn register_rejected_response_tag_deserialization() {
        let json = r#"{"type":"register_rejected","reason":"Pool full"}"#;
        let response: OrchestratorResponse = serde_json::from_str(json).unwrap();

        match response {
            OrchestratorResponse::RegisterRejected(_) => (),
            _ => panic!("Expected RegisterRejected variant"),
        }
    }

    #[test]
    fn error_response_tag_deserialization() {
        let json = r#"{"type":"error","message":"Internal error"}"#;
        let response: OrchestratorResponse = serde_json::from_str(json).unwrap();

        match response {
            OrchestratorResponse::Error(_) => (),
            _ => panic!("Expected Error variant"),
        }
    }

    #[test]
    fn malformed_driver_message_returns_err() {
        let malformed = r#"{"type":"invalid","data":123}"#;
        let result: Result<DriverMessage, _> = serde_json::from_str(malformed);

        assert!(result.is_err());
    }

    #[test]
    fn malformed_orchestrator_response_returns_err() {
        let malformed = r#"{"type":"unknown","value":"test"}"#;
        let result: Result<OrchestratorResponse, _> = serde_json::from_str(malformed);

        assert!(result.is_err());
    }

    #[test]
    fn invalid_json_returns_err() {
        let invalid = r#"not valid json at all"#;
        let result: Result<DriverMessage, _> = serde_json::from_str(invalid);

        assert!(result.is_err());
    }
}
